language: node_js

node_js: 'node'

os: osx

before_script:
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

script:
  - npm install
  - npm run lint
  - npm run build
  - npm run sync:s3
